data <- read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?")
data_part <- subset(data, subset = (as.Date(Date, format="%d/%m/%Y") >= "2007-02-01" & as.Date(Date, format="%d/%m/%Y") <= "2007-02-02"))
png(file="plot2.png",width=480,height=480)
datetime <- paste(data_part$Date, data_part$Time)
datetime <- strptime(datetime, "%d/%m/%Y %H:%M:%S")
data_part<-cbind(datetime,data_part)
png(file="plot2.png",width=480,height=480)
plot(data_part$Global_active_power~data_part$datetime, type = "l",ylab="Global Active Power(kilowatts)")
dev.off()